# Generated by Django 3.2.7 on 2021-10-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='businessAddress',
            new_name='direccionTienda',
        ),
        migrations.RenameField(
            model_name='tienda',
            old_name='storeName',
            new_name='tienda',
        ),
    ]
