# Generated by Django 3.2.7 on 2021-11-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tribus', '0003_aperturavotacion_avatarnt'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tribu',
            field=models.ManyToManyField(to='Tribus.Tribu'),
        ),
    ]
