# Generated by Django 3.2.7 on 2021-09-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodNombre', models.CharField(max_length=200)),
                ('prodID', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField(default=0)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('BR', 'Bicirunners'), ('M', 'Muppies'), ('AL', 'Anilovers'), ('TF', 'Tribufit'), ('TV', 'Travellers')], max_length=30)),
                ('etiqueta', models.CharField(choices=[('MP', 'Marca con Proposito'), ('N', 'Nuevo'), ('MR', 'Mas reconocido')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('prodImagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
