# Generated by Django 3.2.7 on 2021-12-06 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='IsFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='dateAdded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
