# Generated by Django 3.2.7 on 2021-12-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenUrl',
            field=models.CharField(default='assets/Imagenes/yes-png', max_length=200),
        ),
    ]
