# Generated by Django 3.2.7 on 2021-12-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_producto_imagenurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenUrl',
            field=models.CharField(default='assets/logo2.jpg', max_length=200),
        ),
    ]
